CREATE TABLE "Categories" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar
);

CREATE TABLE "Media" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "description" text,
  "category_id" int,
  "file_path" varchar,
  "file_type" varchar,
  "file_size" int,
  "uploaded_at" datetime
);

CREATE TABLE "Users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar,
  "password" varchar
);

CREATE TABLE "Comments" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_id" int,
  "user_id" int,
  "content" text,
  "created_at" datetime
);

CREATE TABLE "Likes" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "media_id" int,
  "user_id" int,
  "liked_at" datetime
);

CREATE TABLE "Playlists" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "name" varchar
);

CREATE TABLE "PlaylistMedia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "playlist_id" int,
  "media_id" int
);

CREATE TABLE "Favorites" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "media_id" int
);

CREATE TABLE "WatchHistory" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "media_id" int,
  "watched_at" datetime
);

CREATE TABLE "UserMedia" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "media_id" int
);

CREATE TABLE "UserThumbnails" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" int,
  "thumbnail_url" varchar
);

ALTER TABLE "Media" ADD FOREIGN KEY ("category_id") REFERENCES "Categories" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "Comments" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "Likes" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Playlists" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "PlaylistMedia" ADD FOREIGN KEY ("playlist_id") REFERENCES "Playlists" ("id");

ALTER TABLE "PlaylistMedia" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "Favorites" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "Favorites" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "WatchHistory" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "WatchHistory" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "UserMedia" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");

ALTER TABLE "UserMedia" ADD FOREIGN KEY ("media_id") REFERENCES "Media" ("id");

ALTER TABLE "UserThumbnails" ADD FOREIGN KEY ("user_id") REFERENCES "Users" ("id");
